# Generated by Django 5.2.12 on 2026-04-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True, verbose_name='Username'),
        ),
    ]
