# Generated by Django 5.2.12 on 2026-05-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_foodcategory_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'ordering': ['name'], 'verbose_name': 'Food Category', 'verbose_name_plural': 'Food Categories'},
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New Order', 'New Order'), ('Being Prepared', 'Being Prepared'), ('Food On The Way', 'Food On The Way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], db_index=True, default='New Order', max_length=30),
        ),
    ]
